version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/mongo:4
      - image: circleci/redis:4

    working_directory: ~/repo

    parallelism: 1

    environment:
      NODE_ENV: test
      MONGO_URL: mongodb://127.0.0.1:27017
      REDIS_URL: redis://127.0.0.1:6379
      CC_TEST_REPORTER_ID: 6075fe79d1f6fe0008112ab3333b1fa3bcfe29e51ea6ef8f82cf88e593e4db50

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Setup test reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build

      - run:
          name: Build
          command: yarn build
      
      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Unit tests
          command: yarn test

      - run:
          name: End to end tests
          command: yarn test:integration

      - run: 
          name: Coverage
          command: |
            yarn coverage:ci
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?